---
  - name: Fail if "{{ nutanix_host }}" is not a Prism Element cluster
    ansible.builtin.fail:
      msg: "this role can only be run from Prism Element (ie. a Nutanix cluster)"
    when:
      - nutanix_endpoint_prism_type != 'pe'

  - name:
    ansible.builtin.fail:
      msg: "the variable 'nutanix_pc_register_pc_ip' is not defined."
    when:
      - nutanix_pc_register_pc_ip is not defined
      - nutanix_pc_register_pc_ip != ""

  - name:
    ansible.builtin.fail:
      msg: "the variable 'nutanix_pc_register_pc_username' is not defined."
    when:
      - nutanix_pc_register_pc_username is not defined
      - nutanix_pc_register_pc_username != ""

  - name:
    ansible.builtin.fail:
      msg: "the variable 'nutanix_pc_register_pc_password' is not defined."
    when:
      - nutanix_pc_register_pc_password is not defined
      - nutanix_pc_register_pc_password != ""
    no_log: True
