---
# tasks file for nutanix_role_prism_central_register_cluster
- import_tasks: setup_api.yml

- name: "Task can only be run against Prism Element"
  ansible.builtin.fail:
    msg: "'nutanix_host' needs to be set to the VIP of a Nutanix cluster. Please check the variable and try again."
  when:
    - nutanix_endpoint_prism_type != 'pe'

- import_tasks: check_variables.yml

- import_tasks: register_cluster.yml

- name: Pause for 30 seconds to allow cluster registeration to finalize
  ansible.builtin.pause:
    seconds: 30
